# Generated by Django 6.0.5 on 2026-08-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0005_alter_material_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('available_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='material.material')),
            ],
        ),
    ]
