"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path):
    """Minimal, dependency-free .env loader - avoids adding python-dotenv
    or django-environ for a handful of key=value lines. Does not override
    a variable already set in the real process environment.
    """
    if not env_path.exists():
        return
    with open(env_path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, value = line.partition('=')
            os.environ.setdefault(key.strip(), value.strip())


_load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').strip().lower() == 'true'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# CORS - explicit allow-list only, sourced from the environment so dev/prod
# never need a code change, just a different .env value. If the variable is
# unset or empty, CORS_ALLOWED_ORIGINS is an empty list, meaning NO origin
# is allowed - deliberately never falling back to allow-all.
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOW_ALL_ORIGINS = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'company',
    'material',
    'category',
    'supplier',
    'purchase',
    'stock',
    'customer',
    'sales',
    'ledger',
    'reports',
    'payment',
    'dispatch',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Django REST Framework
# Phase 3: the default flips from AllowAny to IsAuthenticated - every
# business module now requires a valid JWT at minimum. Views needing a more
# specific rule (Ledger, Payment, Stock writes, master-data delete,
# financial reports, Purchase/Sales confirm+cancel) declare their own
# permission_classes on top of this. Login/refresh explicitly opt back out
# to AllowAny, since they must remain reachable without a token.
#
# Phase 4A: throttling. Login and token-refresh explicitly opt into their
# own ScopedRateThrottle (see accounts/views.py) rather than the general
# Anon/User rates below, since brute-force protection on those two specific
# endpoints needs its own tight, dedicated limit. Every other view keeps
# using the Anon/User defaults. DRF throttling never touches Django Admin -
# Admin is plain Django, not a DRF APIView, so it never runs through this
# machinery at all.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/hour',
        'user': '300/hour',
        'login': '5/minute',
        'refresh': '15/minute',
    },
    'EXCEPTION_HANDLER': 'accounts.exception_handlers.logging_exception_handler',
}

# djangorestframework-simplejwt
# Lifetimes chosen for an internally-operated business ERP, not a
# high-security consumer app: short access-token life limits the exposure
# window of a token that cannot be revoked before it expires; a week-long
# refresh token matches how staff actually use this system (same device,
# repeated logins across a work week) without leaving a stolen refresh
# token dangerous indefinitely. Rotation + blacklist-after-rotation means
# every refresh token can only ever be used once.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# Logging. Console handler deliberately chosen over a file handler - most
# modern deployment platforms (containers, systemd, PaaS) capture
# stdout/stderr directly, so this works in both dev and production without
# needing a separate on-disk log path decided in this phase. Root logger
# catches every module's logging.getLogger(__name__) calls (accounts,
# purchase.services, sales.services, payment.*) without needing each one
# listed individually - none of them disable propagation.
#
# Never log: passwords, JWT access/refresh tokens, SECRET_KEY, the DB
# password, password hashes, or unnecessary personal data. Every logger.*
# call added in this phase (accounts/signals.py, accounts/exception_
# handlers.py, purchase/services.py, sales/services.py, payment/views.py,
# payment/services.py) only ever includes usernames, ids, document numbers,
# and status values - never a credential or secret.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
