# Generated by Django 6.0.5 on 2026-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('BOX', 'Box'), ('SET', 'Set'), ('PKT', 'Packet')], default='PCS', max_length=50, null=True),
        ),
    ]
