# Generated by Django 6.0.5 on 2026-08-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_material_barcode_material_brand_material_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('TON', 'Ton'), ('METER', 'Meter'), ('FEET', 'Feet'), ('BUNDLE', 'Bundle'), ('NOS', 'Numbers'), ('BOX', 'Box'), ('SET', 'Set'), ('PKT', 'Packet')], default='PCS', max_length=50, null=True),
        ),
    ]
