# Generated by Django 6.0.5 on 2026-08-12 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_credit_days_and_more'),
        ('material', '0006_alter_material_gst_percentage_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sales_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sales_discount_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(condition=models.Q(('gst_amount__gte', 0)), name='sales_gst_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='sales_grand_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='salesitem_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='salesitem_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0)), name='salesitem_discount_percentage_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='salesitem_discount_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0)), name='salesitem_taxable_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('gst_percentage__gte', 0)), name='salesitem_gst_percentage_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('gst_amount__gte', 0)), name='salesitem_gst_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='salesitem_line_total_gte_0'),
        ),
    ]
