# Generated by Django 6.0.5 on 2026-08-12 17:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_discount_amount_alter_sales_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
