# Generated by Django 6.0.5 on 2026-08-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_material_unit'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('TON', 'Ton'), ('METER', 'Meter'), ('FEET', 'Feet'), ('BUNDLE', 'Bundle'), ('NOS', 'Numbers'), ('BOX', 'Box'), ('SET', 'Set'), ('PKT', 'Packet')], max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_code_snapshot', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='material.material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchase')),
            ],
        ),
    ]
