# Generated by Django 6.0.5 on 2026-08-12 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_credit_days_and_more'),
        ('ledger', '0001_initial'),
        ('supplier', '0002_alter_supplier_credit_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='ledger_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('supplier__isnull', True)), models.Q(('customer__isnull', True), ('supplier__isnull', False)), _connector='OR'), name='ledger_customer_xor_supplier'),
        ),
    ]
